# Site settings
title: Clackamas Volunteer Search and Rescue
email: your-email@domain.com
url: https://cvsar.github.io
description: "We support Clackamas County Search and Rescue by providing the highest level of training and equipment to ensure the best possible response and outcome for every SAR mission in Clackamas County and beyond."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#ef740d'

# Footer settings
footer: Clackamas Volunteer Search and Rescue

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
